CREATE TABLE `leads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(50),
	`coachingType` varchar(50) NOT NULL,
	`message` text,
	`status` varchar(50) NOT NULL DEFAULT 'new',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `leads_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `users` MODIFY COLUMN `role` enum('CLIENT','COACH','ADMIN') NOT NULL DEFAULT 'CLIENT';--> statement-breakpoint
CREATE INDEX `idx_leads_email` ON `leads` (`email`);--> statement-breakpoint
CREATE INDEX `idx_leads_status` ON `leads` (`status`);--> statement-breakpoint
CREATE INDEX `idx_leads_createdAt` ON `leads` (`createdAt`);--> statement-breakpoint
CREATE INDEX `idx_aiInsights_userId` ON `ai_insights` (`user_id`);--> statement-breakpoint
CREATE INDEX `idx_aiInsights_insightType` ON `ai_insights` (`insight_type`);--> statement-breakpoint
CREATE INDEX `idx_aiInsights_category` ON `ai_insights` (`category`);--> statement-breakpoint
CREATE INDEX `idx_aiInsights_priority` ON `ai_insights` (`priority`);--> statement-breakpoint
CREATE INDEX `idx_aiInsights_isRead` ON `ai_insights` (`is_read`);--> statement-breakpoint
CREATE INDEX `idx_aiInsights_createdAt` ON `ai_insights` (`created_at`);--> statement-breakpoint
CREATE INDEX `idx_aiInsights_userId_isRead_createdAt` ON `ai_insights` (`user_id`,`is_read`,`created_at`);--> statement-breakpoint
CREATE INDEX `idx_aiInsights_userId_priority_createdAt` ON `ai_insights` (`user_id`,`priority`,`created_at`);--> statement-breakpoint
CREATE INDEX `idx_clientPrograms_userId` ON `clientPrograms` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_clientPrograms_programId` ON `clientPrograms` (`programId`);--> statement-breakpoint
CREATE INDEX `idx_clientPrograms_status` ON `clientPrograms` (`status`);--> statement-breakpoint
CREATE INDEX `idx_clientPrograms_createdAt` ON `clientPrograms` (`createdAt`);--> statement-breakpoint
CREATE INDEX `idx_clientPrograms_userId_status` ON `clientPrograms` (`userId`,`status`);--> statement-breakpoint
CREATE INDEX `idx_clientPrograms_userId_createdAt` ON `clientPrograms` (`userId`,`createdAt`);--> statement-breakpoint
CREATE INDEX `idx_conversations_clientId` ON `conversations` (`clientId`);--> statement-breakpoint
CREATE INDEX `idx_conversations_coachId` ON `conversations` (`coachId`);--> statement-breakpoint
CREATE INDEX `idx_conversations_lastMessageAt` ON `conversations` (`lastMessageAt`);--> statement-breakpoint
CREATE INDEX `idx_conversations_clientId_lastMessageAt` ON `conversations` (`clientId`,`lastMessageAt`);--> statement-breakpoint
CREATE INDEX `idx_conversations_coachId_lastMessageAt` ON `conversations` (`coachId`,`lastMessageAt`);--> statement-breakpoint
CREATE INDEX `idx_emailLogs_userId` ON `email_logs` (`user_id`);--> statement-breakpoint
CREATE INDEX `idx_emailLogs_templateId` ON `email_logs` (`template_id`);--> statement-breakpoint
CREATE INDEX `idx_emailLogs_status` ON `email_logs` (`status`);--> statement-breakpoint
CREATE INDEX `idx_emailLogs_sentAt` ON `email_logs` (`sent_at`);--> statement-breakpoint
CREATE INDEX `idx_emailLogs_createdAt` ON `email_logs` (`created_at`);--> statement-breakpoint
CREATE INDEX `idx_emailLogs_userId_status` ON `email_logs` (`user_id`,`status`);--> statement-breakpoint
CREATE INDEX `idx_emailUnsubscribes_userId` ON `email_unsubscribes` (`user_id`);--> statement-breakpoint
CREATE INDEX `idx_emailUnsubscribes_email` ON `email_unsubscribes` (`email`);--> statement-breakpoint
CREATE INDEX `idx_emailUnsubscribes_category` ON `email_unsubscribes` (`category`);--> statement-breakpoint
CREATE INDEX `idx_exercisePlaylists_userId` ON `exercise_playlists` (`user_id`);--> statement-breakpoint
CREATE INDEX `idx_exercisePlaylists_isPublic` ON `exercise_playlists` (`is_public`);--> statement-breakpoint
CREATE INDEX `idx_exercisePlaylists_createdAt` ON `exercise_playlists` (`created_at`);--> statement-breakpoint
CREATE INDEX `idx_formVideos_userId` ON `formVideos` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_formVideos_status` ON `formVideos` (`status`);--> statement-breakpoint
CREATE INDEX `idx_formVideos_uploadedAt` ON `formVideos` (`uploadedAt`);--> statement-breakpoint
CREATE INDEX `idx_formVideos_reviewedAt` ON `formVideos` (`reviewedAt`);--> statement-breakpoint
CREATE INDEX `idx_formVideos_userId_status` ON `formVideos` (`userId`,`status`);--> statement-breakpoint
CREATE INDEX `idx_healthScores_userId` ON `health_scores` (`user_id`);--> statement-breakpoint
CREATE INDEX `idx_healthScores_calculatedAt` ON `health_scores` (`calculated_at`);--> statement-breakpoint
CREATE INDEX `idx_healthScores_userId_calculatedAt` ON `health_scores` (`user_id`,`calculated_at`);--> statement-breakpoint
CREATE INDEX `idx_macroAdjustmentProposals_userId` ON `macro_adjustment_proposals` (`user_id`);--> statement-breakpoint
CREATE INDEX `idx_macroAdjustmentProposals_status` ON `macro_adjustment_proposals` (`status`);--> statement-breakpoint
CREATE INDEX `idx_macroAdjustmentProposals_createdAt` ON `macro_adjustment_proposals` (`created_at`);--> statement-breakpoint
CREATE INDEX `idx_macroAdjustmentProposals_userId_status` ON `macro_adjustment_proposals` (`user_id`,`status`);--> statement-breakpoint
CREATE INDEX `idx_macroAdjustments_userId` ON `macro_adjustments` (`user_id`);--> statement-breakpoint
CREATE INDEX `idx_macroAdjustments_proposalId` ON `macro_adjustments` (`proposal_id`);--> statement-breakpoint
CREATE INDEX `idx_macroAdjustments_createdAt` ON `macro_adjustments` (`created_at`);--> statement-breakpoint
CREATE INDEX `idx_macroAdjustments_userId_createdAt` ON `macro_adjustments` (`user_id`,`created_at`);--> statement-breakpoint
CREATE INDEX `idx_mealLogs_userId` ON `meal_logs` (`user_id`);--> statement-breakpoint
CREATE INDEX `idx_mealLogs_nutritionPlanId` ON `meal_logs` (`nutrition_plan_id`);--> statement-breakpoint
CREATE INDEX `idx_mealLogs_date` ON `meal_logs` (`date`);--> statement-breakpoint
CREATE INDEX `idx_mealLogs_mealType` ON `meal_logs` (`meal_type`);--> statement-breakpoint
CREATE INDEX `idx_mealLogs_createdAt` ON `meal_logs` (`created_at`);--> statement-breakpoint
CREATE INDEX `idx_mealLogs_userId_date` ON `meal_logs` (`user_id`,`date`);--> statement-breakpoint
CREATE INDEX `idx_mealLogs_userId_mealType_date` ON `meal_logs` (`user_id`,`meal_type`,`date`);--> statement-breakpoint
CREATE INDEX `idx_mealPlanRecipes_mealPlanId` ON `mealPlanRecipes` (`mealPlanId`);--> statement-breakpoint
CREATE INDEX `idx_mealPlanRecipes_recipeId` ON `mealPlanRecipes` (`recipeId`);--> statement-breakpoint
CREATE INDEX `idx_mealPlanRecipes_dayOfWeek` ON `mealPlanRecipes` (`dayOfWeek`);--> statement-breakpoint
CREATE INDEX `idx_mealPlanRecipes_mealType` ON `mealPlanRecipes` (`mealType`);--> statement-breakpoint
CREATE INDEX `idx_mealPlanRecipes_mealPlanId_dayOfWeek_mealType` ON `mealPlanRecipes` (`mealPlanId`,`dayOfWeek`,`mealType`);--> statement-breakpoint
CREATE INDEX `idx_mealPlans_userId` ON `mealPlans` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_mealPlans_isActive` ON `mealPlans` (`isActive`);--> statement-breakpoint
CREATE INDEX `idx_mealPlans_startDate` ON `mealPlans` (`startDate`);--> statement-breakpoint
CREATE INDEX `idx_mealPlans_userId_isActive` ON `mealPlans` (`userId`,`isActive`);--> statement-breakpoint
CREATE INDEX `idx_messages_conversationId` ON `messages` (`conversationId`);--> statement-breakpoint
CREATE INDEX `idx_messages_senderId` ON `messages` (`senderId`);--> statement-breakpoint
CREATE INDEX `idx_messages_isRead` ON `messages` (`isRead`);--> statement-breakpoint
CREATE INDEX `idx_messages_createdAt` ON `messages` (`createdAt`);--> statement-breakpoint
CREATE INDEX `idx_messages_conversationId_createdAt` ON `messages` (`conversationId`,`createdAt`);--> statement-breakpoint
CREATE INDEX `idx_messages_senderId_createdAt` ON `messages` (`senderId`,`createdAt`);--> statement-breakpoint
CREATE INDEX `idx_missedSessionReschedules_userId` ON `missedSessionReschedules` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_missedSessionReschedules_originalSessionId` ON `missedSessionReschedules` (`originalSessionId`);--> statement-breakpoint
CREATE INDEX `idx_missedSessionReschedules_newSessionId` ON `missedSessionReschedules` (`newSessionId`);--> statement-breakpoint
CREATE INDEX `idx_missedSessionReschedules_status` ON `missedSessionReschedules` (`status`);--> statement-breakpoint
CREATE INDEX `idx_missedSessionReschedules_originalDate` ON `missedSessionReschedules` (`originalDate`);--> statement-breakpoint
CREATE INDEX `idx_missedSessionReschedules_proposedDate` ON `missedSessionReschedules` (`proposedDate`);--> statement-breakpoint
CREATE INDEX `idx_missedSessionReschedules_userId_status` ON `missedSessionReschedules` (`userId`,`status`);--> statement-breakpoint
CREATE INDEX `idx_monthlyReports_userId` ON `monthly_reports` (`user_id`);--> statement-breakpoint
CREATE INDEX `idx_monthlyReports_month` ON `monthly_reports` (`month`);--> statement-breakpoint
CREATE INDEX `idx_monthlyReports_year` ON `monthly_reports` (`year`);--> statement-breakpoint
CREATE INDEX `idx_monthlyReports_generatedAt` ON `monthly_reports` (`generated_at`);--> statement-breakpoint
CREATE INDEX `idx_monthlyReports_userId_month_year` ON `monthly_reports` (`user_id`,`month`,`year`);--> statement-breakpoint
CREATE INDEX `idx_monthlyReports_userId_year_month` ON `monthly_reports` (`user_id`,`year`,`month`);--> statement-breakpoint
CREATE INDEX `idx_nutritionPlans_userId` ON `nutrition_plans` (`user_id`);--> statement-breakpoint
CREATE INDEX `idx_nutritionPlans_isActive` ON `nutrition_plans` (`is_active`);--> statement-breakpoint
CREATE INDEX `idx_nutritionPlans_startDate` ON `nutrition_plans` (`start_date`);--> statement-breakpoint
CREATE INDEX `idx_onboardingProgress_userId` ON `onboarding_progress` (`user_id`);--> statement-breakpoint
CREATE INDEX `idx_onboardingProgress_step` ON `onboarding_progress` (`step`);--> statement-breakpoint
CREATE INDEX `idx_onboardingProgress_completedAt` ON `onboarding_progress` (`completed_at`);--> statement-breakpoint
CREATE INDEX `idx_onboardingProgress_userId_step` ON `onboarding_progress` (`user_id`,`step`);--> statement-breakpoint
CREATE INDEX `idx_onboardingResponses_userId` ON `onboarding_responses` (`user_id`);--> statement-breakpoint
CREATE INDEX `idx_onboardingResponses_completedAt` ON `onboarding_responses` (`completed_at`);--> statement-breakpoint
CREATE INDEX `idx_playlistExercises_playlistId` ON `playlist_exercises` (`playlist_id`);--> statement-breakpoint
CREATE INDEX `idx_playlistExercises_exerciseId` ON `playlist_exercises` (`exercise_id`);--> statement-breakpoint
CREATE INDEX `idx_playlistExercises_orderIndex` ON `playlist_exercises` (`order_index`);--> statement-breakpoint
CREATE INDEX `idx_playlistExercises_playlistId_orderIndex` ON `playlist_exercises` (`playlist_id`,`order_index`);--> statement-breakpoint
CREATE INDEX `idx_programResources_programId` ON `programResources` (`programId`);--> statement-breakpoint
CREATE INDEX `idx_programResources_type` ON `programResources` (`type`);--> statement-breakpoint
CREATE INDEX `idx_programResources_createdAt` ON `programResources` (`createdAt`);--> statement-breakpoint
CREATE INDEX `idx_programs_category` ON `programs` (`category`);--> statement-breakpoint
CREATE INDEX `idx_programs_createdAt` ON `programs` (`createdAt`);--> statement-breakpoint
CREATE INDEX `idx_progressGoals_clientProgramId` ON `progressGoals` (`clientProgramId`);--> statement-breakpoint
CREATE INDEX `idx_progressGoals_goalType` ON `progressGoals` (`goalType`);--> statement-breakpoint
CREATE INDEX `idx_progressGoals_createdAt` ON `progressGoals` (`createdAt`);--> statement-breakpoint
CREATE INDEX `idx_progressMetrics_clientProgramId` ON `progressMetrics` (`clientProgramId`);--> statement-breakpoint
CREATE INDEX `idx_progressMetrics_metricType` ON `progressMetrics` (`metricType`);--> statement-breakpoint
CREATE INDEX `idx_progressMetrics_recordedAt` ON `progressMetrics` (`recordedAt`);--> statement-breakpoint
CREATE INDEX `idx_progressMetrics_clientProgramId_metricType_recordedAt` ON `progressMetrics` (`clientProgramId`,`metricType`,`recordedAt`);--> statement-breakpoint
CREATE INDEX `idx_progressPredictions_userId` ON `progress_predictions` (`user_id`);--> statement-breakpoint
CREATE INDEX `idx_progressPredictions_goalId` ON `progress_predictions` (`goal_id`);--> statement-breakpoint
CREATE INDEX `idx_progressPredictions_calculatedAt` ON `progress_predictions` (`calculated_at`);--> statement-breakpoint
CREATE INDEX `idx_recipes_category` ON `recipes` (`category`);--> statement-breakpoint
CREATE INDEX `idx_recipes_difficulty` ON `recipes` (`difficulty`);--> statement-breakpoint
CREATE INDEX `idx_recipes_goal` ON `recipes` (`goal`);--> statement-breakpoint
CREATE INDEX `idx_recipes_createdAt` ON `recipes` (`createdAt`);--> statement-breakpoint
CREATE INDEX `idx_referrals_referrerId` ON `referrals` (`referrer_id`);--> statement-breakpoint
CREATE INDEX `idx_referrals_referredId` ON `referrals` (`referred_id`);--> statement-breakpoint
CREATE INDEX `idx_referrals_status` ON `referrals` (`status`);--> statement-breakpoint
CREATE INDEX `idx_referrals_createdAt` ON `referrals` (`created_at`);--> statement-breakpoint
CREATE INDEX `idx_userConsents_userId` ON `user_consents` (`user_id`);--> statement-breakpoint
CREATE INDEX `idx_userConsents_consentDate` ON `user_consents` (`consent_date`);--> statement-breakpoint
CREATE INDEX `idx_userFavoriteRecipes_userId` ON `userFavoriteRecipes` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_userFavoriteRecipes_recipeId` ON `userFavoriteRecipes` (`recipeId`);--> statement-breakpoint
CREATE INDEX `idx_userFavoriteRecipes_addedAt` ON `userFavoriteRecipes` (`addedAt`);--> statement-breakpoint
CREATE INDEX `idx_userFavoriteRecipes_userId_recipeId` ON `userFavoriteRecipes` (`userId`,`recipeId`);--> statement-breakpoint
CREATE INDEX `idx_users_email` ON `users` (`email`);--> statement-breakpoint
CREATE INDEX `idx_users_role` ON `users` (`role`);--> statement-breakpoint
CREATE INDEX `idx_users_createdAt` ON `users` (`createdAt`);--> statement-breakpoint
CREATE INDEX `idx_videoAnalyses_clientId` ON `video_analyses` (`client_id`);--> statement-breakpoint
CREATE INDEX `idx_videoAnalyses_coachId` ON `video_analyses` (`coach_id`);--> statement-breakpoint
CREATE INDEX `idx_videoAnalyses_status` ON `video_analyses` (`status`);--> statement-breakpoint
CREATE INDEX `idx_videoAnalyses_createdAt` ON `video_analyses` (`created_at`);--> statement-breakpoint
CREATE INDEX `idx_videoAnalyses_clientId_status` ON `video_analyses` (`client_id`,`status`);--> statement-breakpoint
CREATE INDEX `idx_videoAnalyses_coachId_status` ON `video_analyses` (`coach_id`,`status`);--> statement-breakpoint
CREATE INDEX `idx_videoAnnotations_videoAnalysisId` ON `video_annotations` (`video_analysis_id`);--> statement-breakpoint
CREATE INDEX `idx_videoAnnotations_coachId` ON `video_annotations` (`coach_id`);--> statement-breakpoint
CREATE INDEX `idx_videoAnnotations_timestamp` ON `video_annotations` (`timestamp`);--> statement-breakpoint
CREATE INDEX `idx_videoAnnotations_videoAnalysisId_timestamp` ON `video_annotations` (`video_analysis_id`,`timestamp`);--> statement-breakpoint
CREATE INDEX `idx_videoMarkers_videoAnalysisId` ON `video_markers` (`video_analysis_id`);--> statement-breakpoint
CREATE INDEX `idx_videoMarkers_coachId` ON `video_markers` (`coach_id`);--> statement-breakpoint
CREATE INDEX `idx_videoMarkers_timestamp` ON `video_markers` (`timestamp`);--> statement-breakpoint
CREATE INDEX `idx_videoMarkers_videoAnalysisId_timestamp` ON `video_markers` (`video_analysis_id`,`timestamp`);--> statement-breakpoint
CREATE INDEX `idx_workoutCompletions_sessionId` ON `workoutCompletions` (`sessionId`);--> statement-breakpoint
CREATE INDEX `idx_workoutCompletions_userId` ON `workoutCompletions` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_workoutCompletions_completedAt` ON `workoutCompletions` (`completedAt`);--> statement-breakpoint
CREATE INDEX `idx_workoutCompletions_userId_completedAt` ON `workoutCompletions` (`userId`,`completedAt`);--> statement-breakpoint
CREATE INDEX `idx_workoutReminders_userId` ON `workoutReminders` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_workoutReminders_sessionId` ON `workoutReminders` (`sessionId`);--> statement-breakpoint
CREATE INDEX `idx_workoutReminders_reminderTime` ON `workoutReminders` (`reminderTime`);--> statement-breakpoint
CREATE INDEX `idx_workoutReminders_isSent` ON `workoutReminders` (`isSent`);--> statement-breakpoint
CREATE INDEX `idx_workoutReminders_userId_reminderTime` ON `workoutReminders` (`userId`,`reminderTime`);--> statement-breakpoint
CREATE INDEX `idx_workoutSessions_userId` ON `workoutSessions` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_workoutSessions_programId` ON `workoutSessions` (`programId`);--> statement-breakpoint
CREATE INDEX `idx_workoutSessions_scheduledDate` ON `workoutSessions` (`scheduledDate`);--> statement-breakpoint
CREATE INDEX `idx_workoutSessions_type` ON `workoutSessions` (`type`);--> statement-breakpoint
CREATE INDEX `idx_workoutSessions_isCompleted` ON `workoutSessions` (`isCompleted`);--> statement-breakpoint
CREATE INDEX `idx_workoutSessions_createdAt` ON `workoutSessions` (`createdAt`);--> statement-breakpoint
CREATE INDEX `idx_workoutSessions_userId_scheduledDate` ON `workoutSessions` (`userId`,`scheduledDate`);--> statement-breakpoint
CREATE INDEX `idx_workoutSessions_userId_isCompleted` ON `workoutSessions` (`userId`,`isCompleted`);