/**
 * Script pour peupler la base de données avec 30 recettes nutritionnelles variées
 * À exécuter via tRPC ou directement
 */

import { getDb } from "./db";
import { recipes, InsertRecipe } from "../drizzle/schema";

const recipeData: InsertRecipe[] = [
  // BREAKFAST - Weight Loss
  {
    name: "Omelette Protéinée aux Légumes",
    description: "Omelette riche en protéines avec légumes frais, parfaite pour démarrer la journée",
    category: "breakfast",
    difficulty: "easy",
    prepTime: 5,
    cookTime: 10,
    servings: 1,
    calories: 280,
    protein: 24,
    carbs: 8,
    fat: 18,
    fiber: 3,
    isVegetarian: 1,
    isGlutenFree: 1,
    isDairyFree: 0,
    isHighProtein: 1,
    isLowCarb: 1,
    goal: "weight_loss",
    ingredients: JSON.stringify([
      { name: "Œufs", quantity: 3, unit: "pièces" },
      { name: "Épinards frais", quantity: 50, unit: "g" },
      { name: "Tomates cerises", quantity: 5, unit: "pièces" },
      { name: "Oignon", quantity: 0.25, unit: "pièce" },
      { name: "Huile d'olive", quantity: 1, unit: "c. à soupe" },
      { name: "Sel et poivre", quantity: 1, unit: "pincée" },
    ]),
    instructions: JSON.stringify([
      "Battre les œufs dans un bol avec sel et poivre",
      "Faire revenir l'oignon émincé dans l'huile d'olive",
      "Ajouter les épinards et tomates cerises, cuire 2 minutes",
      "Verser les œufs battus, cuire à feu moyen 3-4 minutes",
      "Plier l'omelette en deux et servir chaud",
    ]),
    tips: "Ajoutez du fromage feta pour plus de saveur (+ 50 calories)",
  },

  {
    name: "Porridge Protéiné aux Fruits Rouges",
    description: "Porridge d'avoine enrichi en protéines avec fruits rouges antioxydants",
    category: "breakfast",
    difficulty: "easy",
    prepTime: 5,
    cookTime: 10,
    servings: 1,
    calories: 320,
    protein: 22,
    carbs: 42,
    fat: 7,
    fiber: 8,
    isVegetarian: 1,
    isVegan: 0,
    isGlutenFree: 1,
    isHighProtein: 1,
    goal: "muscle_gain",
    ingredients: JSON.stringify([
      { name: "Flocons d'avoine", quantity: 50, unit: "g" },
      { name: "Lait d'amande", quantity: 250, unit: "ml" },
      { name: "Whey protéine vanille", quantity: 20, unit: "g" },
      { name: "Fruits rouges surgelés", quantity: 80, unit: "g" },
      { name: "Miel", quantity: 1, unit: "c. à café" },
      { name: "Graines de chia", quantity: 1, unit: "c. à soupe" },
    ]),
    instructions: JSON.stringify([
      "Faire chauffer le lait d'amande dans une casserole",
      "Ajouter les flocons d'avoine, cuire 5 minutes en remuant",
      "Retirer du feu, incorporer la whey protéine",
      "Ajouter les fruits rouges et graines de chia",
      "Sucrer avec le miel et servir",
    ]),
    tips: "Préparez la veille pour un overnight oats encore plus rapide",
  },

  // LUNCH - Muscle Gain
  {
    name: "Poulet Grillé Quinoa et Brocoli",
    description: "Assiette complète riche en protéines pour la prise de masse musculaire",
    category: "lunch",
    difficulty: "medium",
    prepTime: 10,
    cookTime: 25,
    servings: 1,
    calories: 520,
    protein: 48,
    carbs: 52,
    fat: 12,
    fiber: 9,
    isGlutenFree: 1,
    isDairyFree: 1,
    isHighProtein: 1,
    goal: "muscle_gain",
    ingredients: JSON.stringify([
      { name: "Filet de poulet", quantity: 180, unit: "g" },
      { name: "Quinoa sec", quantity: 60, unit: "g" },
      { name: "Brocoli", quantity: 200, unit: "g" },
      { name: "Huile d'olive", quantity: 1, unit: "c. à soupe" },
      { name: "Ail", quantity: 2, unit: "gousses" },
      { name: "Citron", quantity: 0.5, unit: "pièce" },
      { name: "Paprika", quantity: 1, unit: "c. à café" },
    ]),
    instructions: JSON.stringify([
      "Cuire le quinoa selon les instructions du paquet",
      "Assaisonner le poulet avec paprika, sel, poivre",
      "Griller le poulet à la poêle 6-7 minutes de chaque côté",
      "Cuire le brocoli à la vapeur 8 minutes",
      "Faire revenir l'ail dans l'huile d'olive, ajouter le brocoli",
      "Dresser l'assiette avec quinoa, poulet et brocoli, arroser de citron",
    ]),
    tips: "Préparez plusieurs portions pour meal prep de la semaine",
  },

  {
    name: "Saumon Teriyaki Riz Basmati",
    description: "Saumon riche en oméga-3 avec sauce teriyaki maison et riz complet",
    category: "lunch",
    difficulty: "medium",
    prepTime: 15,
    cookTime: 20,
    servings: 1,
    calories: 580,
    protein: 42,
    carbs: 58,
    fat: 18,
    fiber: 3,
    isDairyFree: 1,
    isHighProtein: 1,
    goal: "muscle_gain",
    ingredients: JSON.stringify([
      { name: "Filet de saumon", quantity: 160, unit: "g" },
      { name: "Riz basmati complet", quantity: 70, unit: "g" },
      { name: "Sauce soja", quantity: 2, unit: "c. à soupe" },
      { name: "Miel", quantity: 1, unit: "c. à soupe" },
      { name: "Gingembre frais", quantity: 10, unit: "g" },
      { name: "Ail", quantity: 1, unit: "gousse" },
      { name: "Graines de sésame", quantity: 1, unit: "c. à café" },
      { name: "Légumes asiatiques", quantity: 150, unit: "g" },
    ]),
    instructions: JSON.stringify([
      "Cuire le riz selon les instructions",
      "Mélanger sauce soja, miel, gingembre et ail râpés",
      "Mariner le saumon 10 minutes dans la moitié de la sauce",
      "Cuire le saumon au four 12 minutes à 180°C",
      "Faire sauter les légumes à la poêle",
      "Servir avec riz, légumes et reste de sauce teriyaki",
    ]),
    tips: "Utilisez du saumon sauvage pour plus d'oméga-3",
  },

  // DINNER - Weight Loss
  {
    name: "Salade César Poulet Grillé Light",
    description: "Version allégée de la salade César classique, riche en protéines",
    category: "dinner",
    difficulty: "easy",
    prepTime: 15,
    cookTime: 10,
    servings: 1,
    calories: 380,
    protein: 38,
    carbs: 22,
    fat: 16,
    fiber: 5,
    isGlutenFree: 0,
    isHighProtein: 1,
    isLowCarb: 1,
    goal: "weight_loss",
    ingredients: JSON.stringify([
      { name: "Filet de poulet", quantity: 150, unit: "g" },
      { name: "Laitue romaine", quantity: 200, unit: "g" },
      { name: "Parmesan râpé", quantity: 20, unit: "g" },
      { name: "Croûtons complets", quantity: 30, unit: "g" },
      { name: "Yaourt grec 0%", quantity: 50, unit: "g" },
      { name: "Moutarde de Dijon", quantity: 1, unit: "c. à café" },
      { name: "Citron", quantity: 0.5, unit: "pièce" },
      { name: "Ail", quantity: 1, unit: "gousse" },
    ]),
    instructions: JSON.stringify([
      "Griller le poulet assaisonné à la poêle",
      "Laver et couper la laitue romaine",
      "Préparer la sauce: mélanger yaourt, moutarde, citron, ail écrasé",
      "Couper le poulet en tranches",
      "Assembler la salade: laitue, poulet, parmesan, croûtons",
      "Arroser de sauce César light et servir",
    ]),
    tips: "Remplacez les croûtons par des pois chiches rôtis pour version sans gluten",
  },

  {
    name: "Wok de Crevettes aux Légumes",
    description: "Wok léger et rapide avec crevettes et légumes croquants",
    category: "dinner",
    difficulty: "easy",
    prepTime: 10,
    cookTime: 10,
    servings: 1,
    calories: 290,
    protein: 32,
    carbs: 18,
    fat: 10,
    fiber: 6,
    isGlutenFree: 1,
    isDairyFree: 1,
    isHighProtein: 1,
    isLowCarb: 1,
    goal: "weight_loss",
    ingredients: JSON.stringify([
      { name: "Crevettes décortiquées", quantity: 180, unit: "g" },
      { name: "Poivron rouge", quantity: 1, unit: "pièce" },
      { name: "Courgette", quantity: 1, unit: "pièce" },
      { name: "Brocoli", quantity: 100, unit: "g" },
      { name: "Sauce soja", quantity: 2, unit: "c. à soupe" },
      { name: "Gingembre frais", quantity: 10, unit: "g" },
      { name: "Ail", quantity: 2, unit: "gousses" },
      { name: "Huile de sésame", quantity: 1, unit: "c. à café" },
    ]),
    instructions: JSON.stringify([
      "Couper tous les légumes en morceaux",
      "Faire chauffer l'huile de sésame dans un wok",
      "Faire revenir ail et gingembre 30 secondes",
      "Ajouter les crevettes, cuire 2-3 minutes",
      "Ajouter les légumes, faire sauter 5 minutes",
      "Ajouter la sauce soja, mélanger et servir",
    ]),
    tips: "Servez avec des nouilles de konjac pour un repas encore plus léger",
  },

  // SNACKS
  {
    name: "Energy Balls Dattes et Amandes",
    description: "Boules d'énergie naturelles sans sucre ajouté, parfaites pré-workout",
    category: "snack",
    difficulty: "easy",
    prepTime: 15,
    cookTime: 0,
    servings: 6,
    calories: 120,
    protein: 4,
    carbs: 16,
    fat: 5,
    fiber: 3,
    isVegetarian: 1,
    isVegan: 1,
    isGlutenFree: 1,
    isDairyFree: 1,
    goal: "endurance",
    ingredients: JSON.stringify([
      { name: "Dattes Medjool", quantity: 150, unit: "g" },
      { name: "Amandes", quantity: 80, unit: "g" },
      { name: "Flocons d'avoine", quantity: 50, unit: "g" },
      { name: "Beurre d'amande", quantity: 2, unit: "c. à soupe" },
      { name: "Cacao en poudre", quantity: 1, unit: "c. à soupe" },
      { name: "Vanille", quantity: 1, unit: "c. à café" },
    ]),
    instructions: JSON.stringify([
      "Dénoyauter les dattes",
      "Mixer tous les ingrédients au robot jusqu'à obtenir une pâte",
      "Former 12 boules avec les mains",
      "Rouler dans la noix de coco râpée (optionnel)",
      "Réfrigérer 1 heure avant de déguster",
      "Conserver au frigo jusqu'à 2 semaines",
    ]),
    tips: "Ajoutez des graines de chia pour plus d'oméga-3",
  },

  {
    name: "Yaourt Grec Protéiné aux Fruits",
    description: "Snack riche en protéines avec yaourt grec et fruits frais",
    category: "snack",
    difficulty: "easy",
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    calories: 210,
    protein: 20,
    carbs: 24,
    fat: 4,
    fiber: 3,
    isVegetarian: 1,
    isGlutenFree: 1,
    isHighProtein: 1,
    goal: "muscle_gain",
    ingredients: JSON.stringify([
      { name: "Yaourt grec 0%", quantity: 200, unit: "g" },
      { name: "Myrtilles fraîches", quantity: 80, unit: "g" },
      { name: "Banane", quantity: 0.5, unit: "pièce" },
      { name: "Miel", quantity: 1, unit: "c. à café" },
      { name: "Amandes effilées", quantity: 10, unit: "g" },
    ]),
    instructions: JSON.stringify([
      "Verser le yaourt grec dans un bol",
      "Ajouter les myrtilles et la banane en rondelles",
      "Arroser de miel",
      "Parsemer d'amandes effilées",
      "Déguster immédiatement",
    ]),
    tips: "Ajoutez une scoop de whey pour encore plus de protéines",
  },

  // More recipes... (continuing with 22 more varied recipes)
  {
    name: "Bowl Buddha Végétarien",
    description: "Bol complet végétarien avec légumes rôtis, quinoa et houmous",
    category: "lunch",
    difficulty: "medium",
    prepTime: 15,
    cookTime: 30,
    servings: 1,
    calories: 480,
    protein: 18,
    carbs: 62,
    fat: 18,
    fiber: 14,
    isVegetarian: 1,
    isVegan: 1,
    isGlutenFree: 1,
    isDairyFree: 1,
    goal: "maintenance",
    ingredients: JSON.stringify([
      { name: "Quinoa", quantity: 60, unit: "g" },
      { name: "Patate douce", quantity: 150, unit: "g" },
      { name: "Pois chiches", quantity: 100, unit: "g" },
      { name: "Avocat", quantity: 0.5, unit: "pièce" },
      { name: "Chou kale", quantity: 50, unit: "g" },
      { name: "Houmous", quantity: 50, unit: "g" },
      { name: "Graines de courge", quantity: 10, unit: "g" },
      { name: "Tahini", quantity: 1, unit: "c. à soupe" },
    ]),
    instructions: JSON.stringify([
      "Cuire le quinoa selon les instructions",
      "Couper la patate douce en cubes, rôtir au four 25 min à 200°C",
      "Rôtir les pois chiches avec épices 20 min",
      "Masser le chou kale avec un peu d'huile d'olive",
      "Assembler le bowl: quinoa, patate douce, pois chiches, kale, avocat",
      "Ajouter houmous, graines et filet de tahini",
    ]),
    tips: "Préparez les ingrédients en avance pour un meal prep efficace",
  },

  {
    name: "Pancakes Protéinés Banane",
    description: "Pancakes moelleux riches en protéines, parfaits pour le petit-déjeuner",
    category: "breakfast",
    difficulty: "easy",
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    calories: 340,
    protein: 28,
    carbs: 38,
    fat: 8,
    fiber: 4,
    isVegetarian: 1,
    isHighProtein: 1,
    goal: "muscle_gain",
    ingredients: JSON.stringify([
      { name: "Banane mûre", quantity: 2, unit: "pièces" },
      { name: "Œufs", quantity: 4, unit: "pièces" },
      { name: "Whey protéine vanille", quantity: 40, unit: "g" },
      { name: "Flocons d'avoine", quantity: 40, unit: "g" },
      { name: "Levure chimique", quantity: 1, unit: "c. à café" },
      { name: "Cannelle", quantity: 1, unit: "c. à café" },
      { name: "Sirop d'érable", quantity: 2, unit: "c. à soupe" },
    ]),
    instructions: JSON.stringify([
      "Écraser les bananes à la fourchette",
      "Ajouter les œufs et mélanger",
      "Incorporer whey, flocons d'avoine, levure et cannelle",
      "Laisser reposer 5 minutes",
      "Cuire des petits pancakes à la poêle 2-3 min de chaque côté",
      "Servir avec sirop d'érable et fruits frais",
    ]),
    tips: "Congelez les pancakes pour un petit-déjeuner rapide toute la semaine",
  },

  {
    name: "Soupe Détox Légumes Verts",
    description: "Soupe légère et détoxifiante aux légumes verts",
    category: "dinner",
    difficulty: "easy",
    prepTime: 10,
    cookTime: 25,
    servings: 2,
    calories: 180,
    protein: 8,
    carbs: 28,
    fat: 4,
    fiber: 8,
    isVegetarian: 1,
    isVegan: 1,
    isGlutenFree: 1,
    isDairyFree: 1,
    isLowCarb: 0,
    goal: "weight_loss",
    ingredients: JSON.stringify([
      { name: "Brocoli", quantity: 200, unit: "g" },
      { name: "Courgette", quantity: 2, unit: "pièces" },
      { name: "Épinards", quantity: 100, unit: "g" },
      { name: "Poireau", quantity: 1, unit: "pièce" },
      { name: "Bouillon de légumes", quantity: 800, unit: "ml" },
      { name: "Ail", quantity: 2, unit: "gousses" },
      { name: "Huile d'olive", quantity: 1, unit: "c. à soupe" },
      { name: "Jus de citron", quantity: 1, unit: "c. à soupe" },
    ]),
    instructions: JSON.stringify([
      "Couper tous les légumes en morceaux",
      "Faire revenir ail et poireau dans l'huile d'olive",
      "Ajouter les autres légumes et le bouillon",
      "Porter à ébullition, puis laisser mijoter 20 minutes",
      "Mixer la soupe jusqu'à consistance lisse",
      "Ajouter le jus de citron et servir chaud",
    ]),
    tips: "Ajoutez des graines de chanvre pour plus de protéines",
  },
];

// Add 20 more recipes to reach 30 total
const additionalRecipes: InsertRecipe[] = [
  {
    name: "Tacos de Poisson Grillé",
    description: "Tacos légers avec poisson blanc grillé et salsa fraîche",
    category: "dinner",
    difficulty: "medium",
    prepTime: 20,
    cookTime: 15,
    servings: 2,
    calories: 420,
    protein: 35,
    carbs: 45,
    fat: 12,
    fiber: 8,
    isDairyFree: 0,
    isHighProtein: 1,
    goal: "maintenance",
    ingredients: JSON.stringify([
      { name: "Filet de cabillaud", quantity: 300, unit: "g" },
      { name: "Tortillas de maïs", quantity: 6, unit: "pièces" },
      { name: "Chou rouge", quantity: 100, unit: "g" },
      { name: "Avocat", quantity: 1, unit: "pièce" },
      { name: "Tomates", quantity: 2, unit: "pièces" },
      { name: "Oignon rouge", quantity: 0.5, unit: "pièce" },
      { name: "Coriandre fraîche", quantity: 20, unit: "g" },
      { name: "Citron vert", quantity: 2, unit: "pièces" },
      { name: "Paprika fumé", quantity: 1, unit: "c. à café" },
    ]),
    instructions: JSON.stringify([
      "Assaisonner le poisson avec paprika, sel, poivre",
      "Griller le poisson 4-5 minutes de chaque côté",
      "Préparer la salsa: tomates, oignon, coriandre, jus de citron",
      "Émincer le chou rouge finement",
      "Écraser l'avocat avec citron vert",
      "Réchauffer les tortillas",
      "Assembler les tacos: poisson, chou, salsa, avocat",
    ]),
    tips: "Utilisez du poisson blanc ferme comme le cabillaud ou le tilapia",
  },

  {
    name: "Curry de Lentilles Corail",
    description: "Curry végétarien riche en protéines végétales et épices",
    category: "dinner",
    difficulty: "easy",
    prepTime: 10,
    cookTime: 25,
    servings: 2,
    calories: 380,
    protein: 18,
    carbs: 58,
    fat: 8,
    fiber: 12,
    isVegetarian: 1,
    isVegan: 1,
    isGlutenFree: 1,
    isDairyFree: 1,
    goal: "weight_loss",
    ingredients: JSON.stringify([
      { name: "Lentilles corail", quantity: 200, unit: "g" },
      { name: "Lait de coco light", quantity: 200, unit: "ml" },
      { name: "Tomates concassées", quantity: 200, unit: "g" },
      { name: "Oignon", quantity: 1, unit: "pièce" },
      { name: "Ail", quantity: 3, unit: "gousses" },
      { name: "Gingembre frais", quantity: 20, unit: "g" },
      { name: "Curry en poudre", quantity: 2, unit: "c. à soupe" },
      { name: "Curcuma", quantity: 1, unit: "c. à café" },
      { name: "Épinards", quantity: 100, unit: "g" },
    ]),
    instructions: JSON.stringify([
      "Faire revenir oignon, ail et gingembre émincés",
      "Ajouter curry et curcuma, faire revenir 1 minute",
      "Ajouter lentilles, tomates et lait de coco",
      "Porter à ébullition, puis laisser mijoter 20 minutes",
      "Ajouter les épinards en fin de cuisson",
      "Servir avec riz basmati ou naan",
    ]),
    tips: "Doublez les quantités pour meal prep de la semaine",
  },

  {
    name: "Smoothie Bowl Açaï",
    description: "Bowl smoothie antioxydant à l'açaï et fruits frais",
    category: "breakfast",
    difficulty: "easy",
    prepTime: 10,
    cookTime: 0,
    servings: 1,
    calories: 380,
    protein: 12,
    carbs: 68,
    fat: 10,
    fiber: 12,
    isVegetarian: 1,
    isVegan: 1,
    isGlutenFree: 1,
    isDairyFree: 1,
    goal: "endurance",
    ingredients: JSON.stringify([
      { name: "Purée d'açaï surgelée", quantity: 100, unit: "g" },
      { name: "Banane surgelée", quantity: 1, unit: "pièce" },
      { name: "Myrtilles surgelées", quantity: 80, unit: "g" },
      { name: "Lait d'amande", quantity: 100, unit: "ml" },
      { name: "Granola", quantity: 30, unit: "g" },
      { name: "Fruits frais variés", quantity: 100, unit: "g" },
      { name: "Noix de coco râpée", quantity: 10, unit: "g" },
      { name: "Graines de chia", quantity: 1, unit: "c. à soupe" },
    ]),
    instructions: JSON.stringify([
      "Mixer açaï, banane, myrtilles et lait d'amande jusqu'à consistance épaisse",
      "Verser dans un bol",
      "Disposer joliment granola, fruits frais, coco et chia",
      "Déguster immédiatement à la cuillère",
    ]),
    tips: "Utilisez des fruits surgelés pour une texture plus épaisse",
  },

  {
    name: "Steak de Bœuf Patate Douce Rôtie",
    description: "Assiette complète avec steak maigre et patate douce",
    category: "dinner",
    difficulty: "medium",
    prepTime: 10,
    cookTime: 30,
    servings: 1,
    calories: 580,
    protein: 52,
    carbs: 48,
    fat: 18,
    fiber: 8,
    isGlutenFree: 1,
    isDairyFree: 1,
    isHighProtein: 1,
    goal: "muscle_gain",
    ingredients: JSON.stringify([
      { name: "Steak de bœuf maigre", quantity: 200, unit: "g" },
      { name: "Patate douce", quantity: 250, unit: "g" },
      { name: "Haricots verts", quantity: 150, unit: "g" },
      { name: "Huile d'olive", quantity: 1, unit: "c. à soupe" },
      { name: "Romarin", quantity: 2, unit: "branches" },
      { name: "Ail", quantity: 2, unit: "gousses" },
      { name: "Beurre", quantity: 10, unit: "g" },
    ]),
    instructions: JSON.stringify([
      "Couper la patate douce en quartiers, rôtir 30 min à 200°C avec romarin",
      "Cuire les haricots verts à la vapeur 8 minutes",
      "Sortir le steak du frigo 30 min avant cuisson",
      "Saisir le steak à feu vif 3-4 min de chaque côté",
      "Laisser reposer 5 minutes sous papier alu",
      "Faire revenir haricots avec ail et beurre",
      "Dresser l'assiette et servir",
    ]),
    tips: "Utilisez un thermomètre pour une cuisson parfaite (55°C pour saignant)",
  },

  {
    name: "Wrap Thon Avocat",
    description: "Wrap rapide et protéiné au thon et avocat",
    category: "lunch",
    difficulty: "easy",
    prepTime: 10,
    cookTime: 0,
    servings: 1,
    calories: 420,
    protein: 32,
    carbs: 38,
    fat: 16,
    fiber: 8,
    isDairyFree: 1,
    isHighProtein: 1,
    goal: "weight_loss",
    ingredients: JSON.stringify([
      { name: "Tortilla complète", quantity: 1, unit: "pièce" },
      { name: "Thon au naturel", quantity: 120, unit: "g" },
      { name: "Avocat", quantity: 0.5, unit: "pièce" },
      { name: "Tomate", quantity: 1, unit: "pièce" },
      { name: "Laitue", quantity: 50, unit: "g" },
      { name: "Oignon rouge", quantity: 0.25, unit: "pièce" },
      { name: "Yaourt grec 0%", quantity: 30, unit: "g" },
      { name: "Citron", quantity: 0.5, unit: "pièce" },
    ]),
    instructions: JSON.stringify([
      "Égoutter le thon et l'émietter",
      "Écraser l'avocat avec jus de citron",
      "Mélanger thon et yaourt grec",
      "Étaler l'avocat sur la tortilla",
      "Ajouter laitue, tomate, oignon, mélange thon",
      "Rouler fermement et couper en deux",
    ]),
    tips: "Ajoutez des graines de tournesol pour du croquant",
  },

  {
    name: "Chia Pudding Mangue Coco",
    description: "Pudding de chia onctueux à la mangue et lait de coco",
    category: "snack",
    difficulty: "easy",
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    calories: 240,
    protein: 6,
    carbs: 32,
    fat: 10,
    fiber: 10,
    isVegetarian: 1,
    isVegan: 1,
    isGlutenFree: 1,
    isDairyFree: 1,
    goal: "maintenance",
    ingredients: JSON.stringify([
      { name: "Graines de chia", quantity: 60, unit: "g" },
      { name: "Lait de coco", quantity: 400, unit: "ml" },
      { name: "Mangue fraîche", quantity: 200, unit: "g" },
      { name: "Miel", quantity: 2, unit: "c. à soupe" },
      { name: "Vanille", quantity: 1, unit: "c. à café" },
      { name: "Noix de coco râpée", quantity: 20, unit: "g" },
    ]),
    instructions: JSON.stringify([
      "Mélanger graines de chia, lait de coco, miel et vanille",
      "Réfrigérer minimum 4 heures ou toute la nuit",
      "Mixer la moitié de la mangue en purée",
      "Couper le reste de la mangue en cubes",
      "Servir le pudding avec purée et cubes de mangue",
      "Parsemer de noix de coco râpée",
    ]),
    tips: "Préparez plusieurs portions pour la semaine",
  },

  {
    name: "Risotto aux Champignons Light",
    description: "Risotto crémeux aux champignons version allégée",
    category: "dinner",
    difficulty: "medium",
    prepTime: 10,
    cookTime: 30,
    servings: 2,
    calories: 420,
    protein: 14,
    carbs: 68,
    fat: 10,
    fiber: 4,
    isVegetarian: 1,
    isGlutenFree: 1,
    goal: "maintenance",
    ingredients: JSON.stringify([
      { name: "Riz arborio", quantity: 160, unit: "g" },
      { name: "Champignons de Paris", quantity: 300, unit: "g" },
      { name: "Bouillon de légumes", quantity: 800, unit: "ml" },
      { name: "Oignon", quantity: 1, unit: "pièce" },
      { name: "Ail", quantity: 2, unit: "gousses" },
      { name: "Vin blanc", quantity: 100, unit: "ml" },
      { name: "Parmesan", quantity: 40, unit: "g" },
      { name: "Huile d'olive", quantity: 2, unit: "c. à soupe" },
      { name: "Persil frais", quantity: 10, unit: "g" },
    ]),
    instructions: JSON.stringify([
      "Faire chauffer le bouillon",
      "Faire revenir oignon et ail dans l'huile d'olive",
      "Ajouter les champignons émincés, cuire 5 minutes",
      "Ajouter le riz, nacrer 2 minutes",
      "Déglacer au vin blanc",
      "Ajouter le bouillon louche par louche en remuant",
      "En fin de cuisson, incorporer parmesan et persil",
    ]),
    tips: "Utilisez des champignons variés (shiitake, pleurotes) pour plus de saveur",
  },

  {
    name: "Barres Protéinées Maison",
    description: "Barres énergétiques protéinées sans cuisson",
    category: "snack",
    difficulty: "easy",
    prepTime: 15,
    cookTime: 0,
    servings: 8,
    calories: 180,
    protein: 12,
    carbs: 18,
    fat: 7,
    fiber: 4,
    isVegetarian: 1,
    isGlutenFree: 1,
    isHighProtein: 1,
    goal: "muscle_gain",
    ingredients: JSON.stringify([
      { name: "Whey protéine vanille", quantity: 100, unit: "g" },
      { name: "Flocons d'avoine", quantity: 150, unit: "g" },
      { name: "Beurre d'amande", quantity: 100, unit: "g" },
      { name: "Miel", quantity: 80, unit: "g" },
      { name: "Pépites de chocolat noir", quantity: 50, unit: "g" },
      { name: "Graines de lin", quantity: 30, unit: "g" },
    ]),
    instructions: JSON.stringify([
      "Mélanger whey et flocons d'avoine",
      "Faire fondre beurre d'amande et miel au micro-ondes",
      "Mélanger tous les ingrédients",
      "Étaler dans un moule rectangulaire",
      "Réfrigérer 2 heures",
      "Découper en 8 barres",
      "Conserver au frigo jusqu'à 2 semaines",
    ]),
    tips: "Enveloppez individuellement pour snacks nomades",
  },

  {
    name: "Poke Bowl Saumon",
    description: "Poke bowl hawaïen au saumon cru mariné",
    category: "lunch",
    difficulty: "medium",
    prepTime: 20,
    cookTime: 15,
    servings: 1,
    calories: 520,
    protein: 38,
    carbs: 52,
    fat: 18,
    fiber: 6,
    isDairyFree: 1,
    isHighProtein: 1,
    goal: "muscle_gain",
    ingredients: JSON.stringify([
      { name: "Saumon sushi grade", quantity: 150, unit: "g" },
      { name: "Riz sushi", quantity: 80, unit: "g" },
      { name: "Avocat", quantity: 0.5, unit: "pièce" },
      { name: "Edamame", quantity: 80, unit: "g" },
      { name: "Concombre", quantity: 0.5, unit: "pièce" },
      { name: "Sauce soja", quantity: 2, unit: "c. à soupe" },
      { name: "Huile de sésame", quantity: 1, unit: "c. à café" },
      { name: "Gingembre mariné", quantity: 20, unit: "g" },
      { name: "Graines de sésame", quantity: 1, unit: "c. à café" },
      { name: "Algue nori", quantity: 1, unit: "feuille" },
    ]),
    instructions: JSON.stringify([
      "Cuire le riz sushi selon les instructions",
      "Couper le saumon en cubes de 2cm",
      "Mariner le saumon 10 min dans sauce soja et huile de sésame",
      "Couper avocat et concombre en tranches",
      "Assembler le bowl: riz, saumon, avocat, edamame, concombre",
      "Ajouter gingembre, sésame et nori émietté",
    ]),
    tips: "Utilisez uniquement du saumon frais de qualité sushi",
  },

  {
    name: "Chili Con Carne Protéiné",
    description: "Chili con carne riche en protéines et fibres",
    category: "dinner",
    difficulty: "easy",
    prepTime: 15,
    cookTime: 40,
    servings: 4,
    calories: 450,
    protein: 42,
    carbs: 38,
    fat: 14,
    fiber: 12,
    isGlutenFree: 1,
    isDairyFree: 1,
    isHighProtein: 1,
    goal: "muscle_gain",
    ingredients: JSON.stringify([
      { name: "Bœuf haché 5%", quantity: 600, unit: "g" },
      { name: "Haricots rouges", quantity: 400, unit: "g" },
      { name: "Tomates concassées", quantity: 800, unit: "g" },
      { name: "Oignon", quantity: 2, unit: "pièces" },
      { name: "Poivron rouge", quantity: 2, unit: "pièces" },
      { name: "Ail", quantity: 4, unit: "gousses" },
      { name: "Piment en poudre", quantity: 2, unit: "c. à soupe" },
      { name: "Cumin", quantity: 1, unit: "c. à soupe" },
      { name: "Paprika fumé", quantity: 1, unit: "c. à soupe" },
    ]),
    instructions: JSON.stringify([
      "Faire revenir oignon et ail émincés",
      "Ajouter le bœuf haché, faire dorer",
      "Ajouter poivron coupé en dés",
      "Ajouter tomates, haricots et épices",
      "Laisser mijoter 30 minutes à feu doux",
      "Servir avec riz basmati ou tortillas",
    ]),
    tips: "Encore meilleur le lendemain, parfait pour meal prep",
  },

  {
    name: "Muffins Banane Avoine",
    description: "Muffins sains à la banane et flocons d'avoine",
    category: "snack",
    difficulty: "easy",
    prepTime: 15,
    cookTime: 25,
    servings: 12,
    calories: 140,
    protein: 5,
    carbs: 22,
    fat: 4,
    fiber: 3,
    isVegetarian: 1,
    goal: "maintenance",
    ingredients: JSON.stringify([
      { name: "Bananes mûres", quantity: 3, unit: "pièces" },
      { name: "Flocons d'avoine", quantity: 200, unit: "g" },
      { name: "Œufs", quantity: 2, unit: "pièces" },
      { name: "Yaourt grec", quantity: 100, unit: "g" },
      { name: "Miel", quantity: 60, unit: "g" },
      { name: "Levure chimique", quantity: 2, unit: "c. à café" },
      { name: "Cannelle", quantity: 1, unit: "c. à café" },
      { name: "Pépites de chocolat", quantity: 50, unit: "g" },
    ]),
    instructions: JSON.stringify([
      "Préchauffer le four à 180°C",
      "Mixer les flocons d'avoine en farine",
      "Écraser les bananes",
      "Mélanger tous les ingrédients",
      "Répartir dans 12 moules à muffins",
      "Cuire 25 minutes",
      "Laisser refroidir avant de démouler",
    ]),
    tips: "Congelez les muffins pour un snack rapide",
  },

  {
    name: "Salade Quinoa Méditerranéenne",
    description: "Salade complète au quinoa et légumes méditerranéens",
    category: "lunch",
    difficulty: "easy",
    prepTime: 15,
    cookTime: 15,
    servings: 2,
    calories: 420,
    protein: 16,
    carbs: 52,
    fat: 18,
    fiber: 10,
    isVegetarian: 1,
    isVegan: 0,
    isGlutenFree: 1,
    goal: "weight_loss",
    ingredients: JSON.stringify([
      { name: "Quinoa", quantity: 120, unit: "g" },
      { name: "Tomates cerises", quantity: 200, unit: "g" },
      { name: "Concombre", quantity: 1, unit: "pièce" },
      { name: "Poivron jaune", quantity: 1, unit: "pièce" },
      { name: "Olives noires", quantity: 50, unit: "g" },
      { name: "Feta", quantity: 80, unit: "g" },
      { name: "Oignon rouge", quantity: 0.5, unit: "pièce" },
      { name: "Huile d'olive", quantity: 3, unit: "c. à soupe" },
      { name: "Citron", quantity: 1, unit: "pièce" },
      { name: "Menthe fraîche", quantity: 10, unit: "g" },
    ]),
    instructions: JSON.stringify([
      "Cuire le quinoa selon les instructions",
      "Couper tous les légumes en petits dés",
      "Émietter la feta",
      "Préparer la vinaigrette: huile d'olive, jus de citron, menthe",
      "Mélanger quinoa refroidi, légumes et feta",
      "Arroser de vinaigrette et servir frais",
    ]),
    tips: "Parfait pour lunch box, se conserve 3 jours au frigo",
  },

  {
    name: "Burger Poulet Avocat Maison",
    description: "Burger maison au poulet grillé et avocat",
    category: "dinner",
    difficulty: "medium",
    prepTime: 20,
    cookTime: 15,
    servings: 2,
    calories: 520,
    protein: 45,
    carbs: 42,
    fat: 18,
    fiber: 8,
    isHighProtein: 1,
    goal: "muscle_gain",
    ingredients: JSON.stringify([
      { name: "Filet de poulet", quantity: 300, unit: "g" },
      { name: "Pains burger complets", quantity: 2, unit: "pièces" },
      { name: "Avocat", quantity: 1, unit: "pièce" },
      { name: "Tomate", quantity: 1, unit: "pièce" },
      { name: "Laitue", quantity: 4, unit: "feuilles" },
      { name: "Oignon rouge", quantity: 0.5, unit: "pièce" },
      { name: "Yaourt grec 0%", quantity: 50, unit: "g" },
      { name: "Moutarde", quantity: 1, unit: "c. à soupe" },
      { name: "Paprika", quantity: 1, unit: "c. à café" },
    ]),
    instructions: JSON.stringify([
      "Assaisonner le poulet avec paprika, sel, poivre",
      "Griller le poulet 6-7 minutes de chaque côté",
      "Préparer la sauce: yaourt grec + moutarde",
      "Écraser l'avocat",
      "Faire griller légèrement les pains",
      "Assembler: pain, sauce, laitue, poulet, tomate, oignon, avocat",
    ]),
    tips: "Servez avec frites de patate douce au four",
  },

  {
    name: "Crêpes Protéinées au Chocolat",
    description: "Crêpes riches en protéines avec sauce chocolat",
    category: "dessert",
    difficulty: "easy",
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    calories: 280,
    protein: 22,
    carbs: 32,
    fat: 6,
    fiber: 4,
    isVegetarian: 1,
    isHighProtein: 1,
    goal: "muscle_gain",
    ingredients: JSON.stringify([
      { name: "Œufs", quantity: 4, unit: "pièces" },
      { name: "Whey protéine chocolat", quantity: 60, unit: "g" },
      { name: "Flocons d'avoine mixés", quantity: 80, unit: "g" },
      { name: "Lait d'amande", quantity: 300, unit: "ml" },
      { name: "Cacao en poudre", quantity: 2, unit: "c. à soupe" },
      { name: "Banane", quantity: 2, unit: "pièces" },
      { name: "Beurre de cacahuète", quantity: 40, unit: "g" },
    ]),
    instructions: JSON.stringify([
      "Mixer œufs, whey, flocons d'avoine et lait",
      "Laisser reposer 5 minutes",
      "Cuire des crêpes fines à la poêle",
      "Préparer la sauce: cacao + beurre de cacahuète + eau chaude",
      "Garnir les crêpes de rondelles de banane",
      "Arroser de sauce chocolat et servir",
    ]),
    tips: "Ajoutez des pépites de chocolat noir pour plus de gourmandise",
  },

  {
    name: "Soupe Miso aux Légumes",
    description: "Soupe japonaise réconfortante au miso et tofu",
    category: "dinner",
    difficulty: "easy",
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    calories: 180,
    protein: 14,
    carbs: 18,
    fat: 6,
    fiber: 4,
    isVegetarian: 1,
    isVegan: 1,
    isGlutenFree: 0,
    isDairyFree: 1,
    goal: "weight_loss",
    ingredients: JSON.stringify([
      { name: "Pâte miso", quantity: 40, unit: "g" },
      { name: "Tofu ferme", quantity: 200, unit: "g" },
      { name: "Champignons shiitake", quantity: 100, unit: "g" },
      { name: "Algue wakame", quantity: 10, unit: "g" },
      { name: "Oignon vert", quantity: 2, unit: "tiges" },
      { name: "Bouillon dashi", quantity: 800, unit: "ml" },
      { name: "Sauce soja", quantity: 1, unit: "c. à soupe" },
    ]),
    instructions: JSON.stringify([
      "Faire chauffer le bouillon dashi",
      "Couper le tofu en cubes",
      "Émincer les champignons",
      "Réhydrater l'algue wakame",
      "Ajouter tofu, champignons et algue au bouillon",
      "Diluer le miso dans un peu de bouillon, ajouter à la soupe",
      "Ajouter oignon vert émincé et sauce soja",
      "Servir immédiatement sans faire bouillir",
    ]),
    tips: "Ne jamais faire bouillir après ajout du miso pour préserver les probiotiques",
  },

  {
    name: "Tartine Saumon Fumé Avocat",
    description: "Tartine gourmande au saumon fumé et avocat",
    category: "breakfast",
    difficulty: "easy",
    prepTime: 10,
    cookTime: 0,
    servings: 1,
    calories: 380,
    protein: 24,
    carbs: 32,
    fat: 18,
    fiber: 8,
    isHighProtein: 1,
    goal: "maintenance",
    ingredients: JSON.stringify([
      { name: "Pain complet", quantity: 2, unit: "tranches" },
      { name: "Saumon fumé", quantity: 80, unit: "g" },
      { name: "Avocat", quantity: 0.5, unit: "pièce" },
      { name: "Fromage frais 0%", quantity: 40, unit: "g" },
      { name: "Citron", quantity: 0.5, unit: "pièce" },
      { name: "Aneth frais", quantity: 5, unit: "g" },
      { name: "Câpres", quantity: 1, unit: "c. à café" },
      { name: "Poivre noir", quantity: 1, unit: "pincée" },
    ]),
    instructions: JSON.stringify([
      "Faire griller légèrement le pain",
      "Tartiner de fromage frais",
      "Écraser l'avocat avec jus de citron",
      "Étaler l'avocat sur le fromage",
      "Disposer le saumon fumé",
      "Parsemer d'aneth, câpres et poivre",
    ]),
    tips: "Ajoutez un œuf poché pour encore plus de protéines",
  },

  {
    name: "Pad Thaï aux Crevettes",
    description: "Nouilles thaïlandaises sautées aux crevettes",
    category: "dinner",
    difficulty: "medium",
    prepTime: 20,
    cookTime: 15,
    servings: 2,
    calories: 480,
    protein: 32,
    carbs: 58,
    fat: 12,
    fiber: 4,
    isDairyFree: 1,
    isHighProtein: 1,
    goal: "maintenance",
    ingredients: JSON.stringify([
      { name: "Nouilles de riz", quantity: 200, unit: "g" },
      { name: "Crevettes", quantity: 300, unit: "g" },
      { name: "Œufs", quantity: 2, unit: "pièces" },
      { name: "Pousses de soja", quantity: 100, unit: "g" },
      { name: "Oignon vert", quantity: 3, unit: "tiges" },
      { name: "Cacahuètes concassées", quantity: 40, unit: "g" },
      { name: "Sauce tamarin", quantity: 3, unit: "c. à soupe" },
      { name: "Sauce poisson", quantity: 2, unit: "c. à soupe" },
      { name: "Sucre de palme", quantity: 1, unit: "c. à soupe" },
      { name: "Citron vert", quantity: 1, unit: "pièce" },
    ]),
    instructions: JSON.stringify([
      "Faire tremper les nouilles selon instructions",
      "Préparer la sauce: tamarin, sauce poisson, sucre",
      "Faire sauter les crevettes, réserver",
      "Faire brouiller les œufs, réserver",
      "Faire sauter nouilles égouttées avec la sauce",
      "Ajouter crevettes, œufs, pousses de soja",
      "Servir avec cacahuètes, oignon vert et citron vert",
    ]),
    tips: "Utilisez du tamarin frais pour une saveur authentique",
  },

  {
    name: "Mousse Chocolat Avocat",
    description: "Mousse au chocolat saine à base d'avocat",
    category: "dessert",
    difficulty: "easy",
    prepTime: 10,
    cookTime: 0,
    servings: 4,
    calories: 220,
    protein: 4,
    carbs: 28,
    fat: 12,
    fiber: 6,
    isVegetarian: 1,
    isVegan: 1,
    isGlutenFree: 1,
    isDairyFree: 1,
    goal: "maintenance",
    ingredients: JSON.stringify([
      { name: "Avocats mûrs", quantity: 2, unit: "pièces" },
      { name: "Cacao en poudre", quantity: 40, unit: "g" },
      { name: "Sirop d'érable", quantity: 80, unit: "ml" },
      { name: "Lait d'amande", quantity: 100, unit: "ml" },
      { name: "Extrait de vanille", quantity: 1, unit: "c. à café" },
      { name: "Sel", quantity: 1, unit: "pincée" },
    ]),
    instructions: JSON.stringify([
      "Mixer tous les ingrédients au blender jusqu'à consistance lisse",
      "Goûter et ajuster le sucre si nécessaire",
      "Répartir dans 4 verrines",
      "Réfrigérer minimum 2 heures",
      "Décorer avec copeaux de chocolat noir",
      "Servir frais",
    ]),
    tips: "Personne ne devinera qu'il y a de l'avocat !",
  },

  {
    name: "Falafels Maison Sauce Tahini",
    description: "Falafels croustillants aux pois chiches avec sauce tahini",
    category: "lunch",
    difficulty: "medium",
    prepTime: 20,
    cookTime: 25,
    servings: 4,
    calories: 420,
    protein: 18,
    carbs: 52,
    fat: 16,
    fiber: 12,
    isVegetarian: 1,
    isVegan: 1,
    isGlutenFree: 1,
    isDairyFree: 1,
    goal: "maintenance",
    ingredients: JSON.stringify([
      { name: "Pois chiches secs", quantity: 300, unit: "g" },
      { name: "Oignon", quantity: 1, unit: "pièce" },
      { name: "Ail", quantity: 4, unit: "gousses" },
      { name: "Persil frais", quantity: 40, unit: "g" },
      { name: "Coriandre fraîche", quantity: 40, unit: "g" },
      { name: "Cumin", quantity: 2, unit: "c. à café" },
      { name: "Tahini", quantity: 80, unit: "g" },
      { name: "Citron", quantity: 2, unit: "pièces" },
      { name: "Pains pita", quantity: 4, unit: "pièces" },
    ]),
    instructions: JSON.stringify([
      "Faire tremper les pois chiches 12h, égoutter",
      "Mixer pois chiches, oignon, ail, herbes et épices",
      "Former 16 falafels",
      "Cuire au four 25 min à 200°C en retournant à mi-cuisson",
      "Préparer sauce tahini: tahini, jus de citron, eau, sel",
      "Servir dans pains pita avec salade et sauce",
    ]),
    tips: "Utilisez des pois chiches secs, pas en conserve, pour la texture",
  },

  {
    name: "Overnight Oats Beurre de Cacahuète",
    description: "Overnight oats protéinés au beurre de cacahuète",
    category: "breakfast",
    difficulty: "easy",
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    calories: 420,
    protein: 20,
    carbs: 52,
    fat: 14,
    fiber: 10,
    isVegetarian: 1,
    isHighProtein: 1,
    goal: "muscle_gain",
    ingredients: JSON.stringify([
      { name: "Flocons d'avoine", quantity: 60, unit: "g" },
      { name: "Lait d'amande", quantity: 200, unit: "ml" },
      { name: "Whey protéine vanille", quantity: 20, unit: "g" },
      { name: "Beurre de cacahuète", quantity: 20, unit: "g" },
      { name: "Banane", quantity: 1, unit: "pièce" },
      { name: "Graines de chia", quantity: 1, unit: "c. à soupe" },
      { name: "Cannelle", quantity: 0.5, unit: "c. à café" },
    ]),
    instructions: JSON.stringify([
      "Mélanger flocons d'avoine, lait, whey, chia et cannelle",
      "Ajouter le beurre de cacahuète",
      "Réfrigérer toute la nuit",
      "Le matin, ajouter la banane en rondelles",
      "Déguster froid ou réchauffer 1 minute au micro-ondes",
    ]),
    tips: "Préparez 5 pots le dimanche pour toute la semaine",
  },
];

const allRecipes = [...recipeData, ...additionalRecipes];

async function seedRecipes() {
  console.log("[Seed Recipes] Starting recipe seeding...");

  const db = await getDb();
  if (!db) {
    console.error("[Seed Recipes] Database not available");
    return;
  }

  try {
    // Check if recipes already exist
    const existingRecipes = await db.select().from(recipes);

    if (existingRecipes.length > 0) {
      console.log(`[Seed Recipes] Found ${existingRecipes.length} existing recipes, skipping seed`);
      return;
    }

    // Insert all recipes
    for (const recipe of allRecipes) {
      await db.insert(recipes).values(recipe);
      console.log(`[Seed Recipes] Created recipe: ${recipe.name}`);
    }

    console.log(`[Seed Recipes] Successfully created ${allRecipes.length} recipes`);
  } catch (error) {
    console.error("[Seed Recipes] Error seeding recipes:", error);
  }
}

// Export for use in tRPC

export { seedRecipes, allRecipes };
